PreCommit:
  RuboCop:
    enabled: true
  RSpec:
    enabled: true
  TrailingWhitespace:
    enabled: true
  EmptyLines:
    enabled: true
  BundleAudit:
    enabled: false
  Brakeman:
    enabled: false

CommitMsg:
  TextWidth:
    enabled: true
    max_width: 72
  CapitalizedSubject:
    enabled: true
  SingleLineSubject:
    enabled: true