services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: libellusDB
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_HOST: database
      DATABASE_NAME: libellusDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      database:
        condition: service_healthy
    command: ["./bin/thrust", "./bin/rails", "server"]
    stdin_open: true
    tty: true

volumes:
  pg_data:
